<?php
/**
 * @file
 * Provides a Views plugin for displaying images in a Mosaic Grid layout.
 */

/**
 * Implements hook_autoload_info().
 */
function mosaic_grid_autoload_info() {
  return array(
    'views_plugin_style_mosaic_grid' => 'views_plugin_style_mosaic_grid.inc',
  );
}

/**
 * Load include file.
 */
module_load_include('inc', 'mosaic_grid', 'mosaic_grid.views');

/**
 * Implements hook_views_api().
 */
function mosaic_grid_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'mosaic_grid'),
    'template_path' => backdrop_get_path('module', 'mosaic_grid'),
  );
}

/**
 * Implements hook_library_info().
 */
function mosaic_grid_library_info() {
  $libraries['flexImages'] = array(
    'title' => 'Flex Images',
    'website' => 'https://goodies.pixabay.com/jquery/flex-images/demo.html',
    'version' => '1.0.4',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.min.js' => array(
        'weight' => 1,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.css' => array(),
    ),
  );

  $libraries['lazyloadxt'] = array(
    'title' => 'Lazy Load XT',
    'website' => 'http://ressio.github.io/lazy-load-xt/',
    'version' => '1.1.0',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.min.js' => array(
        'weight' => 2,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.fadein.min.css' => array(),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_menu().
 */
function mosaic_grid_menu() {
  $items['admin/config/media/mosaic_grid'] = array(
    'title' => 'Mosaic Grid',
    'description' => 'Configure global options for Mosaic Grid views formatter.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mosaic_grid_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mosaic_grid.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_config_info().
 */
function mosaic_grid_config_info() {
  return array(
    'mosaic_grid.settings' => array(
      'label' => t('Mosaic Grid settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_theme().
 * Registers theme function that renders a single
 * item(image with a caption) of the mosaic grid.
 */
function mosaic_grid_theme($existing, $type, $theme, $path) {
  return array(
    'mosaic_grid_item' => array(
      'variables' => array(
        'image_item'      => NULL,
        'image_field_id'  => '',
        'image_style'     => '',
        'text_item'       => NULL,
        'text_field'      => NULL,
        'options' => array(
          'gap' => 0,
          'captions' => array(
            'display' => 'static',
            'source'  => '',
          ),
        ),
      ),
      'file' => 'mosaic_grid_item.theme.inc',
    ),
  );
}


/**
 * Implements hook_views_pre_render().
 * Displays warning about styles in preview mode.
 */
function mosaic_grid_views_pre_render(&$view) {
  if (isset($view->preview)) {
    $options = $view->style_plugin->options;
    if (!empty($options['captions']['source'])) {
      // Get deafault and views theme names.
      $default_theme_name = config_get('system.core', 'theme_default');
      $views_theme_name = config_get('views_ui.settings', 'custom_theme');
      if (!$views_theme_name || $views_theme_name == '_default')
        $views_theme_name = config_get('system.core', 'admin_theme');
      // Show warning if views and default themes are not the same.
      if ($views_theme_name != $default_theme_name) {
        $themes = list_themes();
        $views_human_name = $themes[$views_theme_name]->info['name'];
        $default_human_name = $themes[$default_theme_name]->info['name'];
        backdrop_set_message(
          t("This preview uses styles from theme %admin. Make sure to check the final look of captions with your site's default theme (%default).", array('%admin' => $views_human_name, '%default' => $default_human_name)),
          'warning'
        );
      }
    }
  }
}


/**
 * Preprocess function for module's template views_view_mosaic-grid.tpl.php.
 * Loads libraries and generates css according to the style plugin options.
 */
function template_preprocess_views_view_mosaic_grid(&$vars) {
  // Get current view.
  $view = $vars['view'];
  // Get style plugin for this view.
  $style_plugin = $view->style_plugin;
  // Get config and plugin options.
  $config  = config('mosaic_grid.settings');
  $options = $vars['options'];

  // Create unique id for the mosaic grid.
  $mosaic_id = 'mosaic-grid-' . $view->name . '-' . $view->current_display;

  // Store data in variables to be easily accessible by the template.
  $vars['rendered_mosaic_items'] = $style_plugin->rendered_mosaic_items;
  $vars['mosaic_id']             = $mosaic_id;
  $vars['lazyload_enabled']      = $config->get('lazyload_enabled');

  // Create settings array for js.
  $js_settings = array(
    'mosaic_grid' => array(
      $mosaic_id => array(
        'max_row_height' => $options['max_row_height'],
        'max_rows'       => $options['max_rows'],
        'truncate'       => $options['truncate'],
      ),
    ),
  );

  // Get module's directory.
  $module_dir = backdrop_get_path('module', 'mosaic_grid');

  // Add flexImages jQuery library.
  backdrop_add_library('mosaic_grid', 'flexImages', FALSE);

  // If lazyload is enabled then do all related setup.
  if ($config->get('lazyload_enabled')) {
    // Add lazyload javascript settings.
    $js_settings['mosaic_grid']['lazyload'] = array(
        'edgeY' => $config->get('lazyload_edgeY'),
      );

    // Add lazyLoadXt library.
    backdrop_add_library('mosaic_grid', 'lazyloadxt', FALSE);

    // Check loader style setting.
    $loader_style = $config->get('loader_style');

    // If one of the loader styles selected then add it's CSS file.
    if (!empty($loader_style)) {
      backdrop_add_css($module_dir . '/css/mosaic_grid_loader_' . $loader_style . '.css');

      // Add color customisation as inline css.
      $color_hex = $config->get('loader_color');
      switch ($loader_style) {
        case 'spinning_ring':
        case 'spinning_ring_thin':
          // Check if color is a valid hex color and convert it to rgb.
          if (Color::validateHex($color_hex)) {
            $color = Color::hexToRgb($color_hex);
          }
          else {
            $color = Color::hexToRgb('#ffffff');
          }
          $loader_custom_css = "
            .mosaic-grid-loader {
              border-color: rgba({$color['red']}, {$color['green']}, {$color['blue']}, 0.2);
              border-left-color: {$color_hex};
            }";
          break;

        case 'floating_balls':
        case 'three_dots':
        case 'square_blocks':
          $loader_custom_css = "
            .mosaic-grid-loader {
              color: {$color_hex};
            }";
          break;

        case 'vertical_blocks':
          $loader_custom_css = "
            .mosaic-grid-loader,
            .mosaic-grid-loader:before,
            .mosaic-grid-loader:after {
              background: {$color_hex};
              color: {$color_hex};
            }";
          break;
      }
    }
  }

  // Add settings and load js to initiate plugins.
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_js($module_dir . '/js/mosaic_grid.js');

  // Load module's styles.
  backdrop_add_css($module_dir . '/css/mosaic_grid.css');

  // The rest of the function code below generates customized CSS, based on
  // configuration, and module options.
  $custom_css = empty($loader_custom_css) ? '' : $loader_custom_css;

  // Set caption height options.
  $height = '';
  switch ($options['captions']['height']['option']) {
    case 'fixed':
      $height .= 'height: ' . $options['captions']['height']['value'] . 'em;';
      // Intentionally no break here. Max-height is needed anyway.
    case 'limit':
      $height .= 'max-height: ' . $options['captions']['height']['value'] . 'em;';
      break;
  }

  // Create style overrides if caption style is set to custom.
  if ($config->get('caption_style_override')) {
    // Get settings for caption style.
    $font_color  = $config->get('caption_font_color');
    $bg_color    = $config->get('caption_background_color');
    $opacity     = $config->get('caption_opacity') / 100;
    $font_size   = $config->get('caption_font_size');
    $padding     = $config->get('caption_padding');
    $padding_h   = $options['captions']['no_padding_h'] ? 0 : $padding * 1.5;

    // Check if background color is a valid hex color and convert it to rgb.
    if (Color::validateHex($bg_color)) {
      $color = Color::hexToRgb($bg_color);
    }
    else {
      $color = Color::hexToRgb('#000000');
    }
    // Create css with inserted values.
    $custom_css .= "
      .mosaic-grid-caption {
        color: {$font_color};
        background: rgba({$color['red']}, {$color['green']}, {$color['blue']}, {$opacity});
        font-size: {$font_size}em;
        {$height}
        padding: {$padding}em {$padding_h}em;
      }
      .mosaic-grid-caption * {
        color: {$font_color} !important;
      }";
  }
  else {
    if ($options['captions']['no_padding_h']) {
      // Make 'no horisontal padding' work even when no custom caption style set.
      $custom_css .= "
        .mosaic-grid-caption {
          padding-left: 0em;
          padding-right: 0em;
        }";
    }
    if ($height != '') {
      $custom_css .= "
        .mosaic-grid-caption {
          {$height}
        }";
    }
  }
  // Minify generated stylesheet and add it to the page.
  if ($custom_css != '') {
    $vars['custom_css'] = backdrop_load_stylesheet_content($custom_css, TRUE);
    backdrop_add_css($vars['custom_css'], array('type' => 'inline'));
  }
}


/**
 * Implements hook_preprocess_views_view_field().
 * Catches image field data and related caption data, renders
 * Mosaic grid item and stores it in array for the view template.
 */
function mosaic_grid_preprocess_views_view_field(&$variables) {
  $view         = $variables['view'];
  $style_plugin = $view->style_plugin;

  // Run the code only if Mosaic Grid plugin is used.
  if ($style_plugin->plugin_name != 'mosaic_grid') {
    return;
  }

  $row_index = $view->row_index;
  $row_data  = $variables['row'];
  $field     = $variables['field'];

  if (!empty($field->field_info['type'])) {
    if ($field->field_info['type'] == 'image') {
      $image_field_id = $field->options['id'];
      // Obtain text source for image caption if defined.
      $caption_source = '';
      if (!empty($style_plugin->options['captions']['source'][$image_field_id])) {
        $caption_source = $style_plugin->options['captions']['source'][$image_field_id];
      }
      // If text is a field, not alt or title tag, get the text field.
      if (!in_array($caption_source, ['', 'alt_tag', 'title_tag'])) {
        $text_field = $view->field[$caption_source];
        if (method_exists($text_field, 'get_items')) {
          // Get array of values(items) for the text field.
          $text_items = $text_field->get_items($row_data);
        }
        else {
          // For title and custom text fields get flat value.
          // Put the value in array for consistency, so that it 
          // is used for one image only.
          $text_items = array($text_field->render($row_data));
        }
      }
      // Iterate over each image field value (item).
      $image_items = $field->get_items($row_data);
      foreach ($image_items as $i => $image_item) {
        // Create a Mosaic Grid item with an image and a caption text.
        $mosaic_grid_item = theme(
          'mosaic_grid_item',
          array(
              'image_item'       => $image_item,
              'image_field_id'   => $image_field_id,
              'image_style'      => $style_plugin->image_styles[$image_field_id],
              'text_item'        => empty($text_items[$i]) ? NULL : $text_items[$i],
              'text_field'       => empty($text_field)     ? NULL : $text_field,
              'options'          => $style_plugin->options,
          )
        );
        // Save the item to an array that will be used for gallery generation.
        $style_plugin->rendered_mosaic_items[] = $mosaic_grid_item;
      }
    }
  }
}


/**
 * Implements hook_preprocess_image().
 * Prepares images for lazy loading script.
 */
function mosaic_grid_preprocess_image(&$variables) {
  // Check if there is an active view with this style plugin.
  $view = views_get_current_view();
  if (!isset($view) || !is_object($view)) return;
  if ($view->style_plugin->plugin_name != 'mosaic_grid') return;

  // Check if image lazy loading is enabled in module settings.
  $lazyload = config_get('mosaic_grid.settings', 'lazyload_enabled');
  if (!$lazyload) return;

  // Change src attribute to blank image and assign actual image url to lazy-src.
  // This is required for lazy loading js plugin to work.
  $path_or_uri = $variables['uri'] ? $variables['uri'] : $variables['path'];
  $variables['attributes']['lazy-src'] = file_create_url($path_or_uri);
  $variables['attributes']['src'] = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";
}

